export type Category = Categories | string;

export enum Categories {
    Ammunition = 'Ammunition',
    Armor = 'Armor',
    Assembly = 'Assembly',
    Blacksmithing = 'Blacksmithing',
    Blade = 'Blade',
    Carpentry = 'Carpentry',
    Carving = 'Carving',
    Cooking = 'Cooking',
    Cookware = 'Cookware',
    Electrical = 'Electrical',
    Farming = 'Farming',
    Fishing = 'Fishing',
    Glassmaking = 'Glassmaking',
    Knapping = 'Knapping',
    Masonry = 'Masonry',
    Medical = 'Medical',
    Metalworking = 'Metalworking',
    Miscellaneous = 'Miscellaneous',
    Packing = 'Packing',
    Pottery = 'Pottery',
    Repair = 'Repair',
    Survival = 'Survival',
    Tailoring = 'Tailoring',
    Tools = 'Tools',
    Weaponry = 'Weaponry',
}
