export type ItemType =
    | 'AlarmClock'
    | 'AlarmClockClothing'
    | 'Clothing'
    | 'Container'
    | 'Drainable'
    | 'Food'
    | 'Key'
    | 'Literature'
    | 'Map'
    | 'Moveable'
    | 'Normal'
    | 'Radio'
    | 'Weapon'
    | 'WeaponPart';
